name: Python application test with GitHub Action

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          make install

      - name: Lint with pylint
        run: |
          make lint

      - name: Run tests with pytest
        run: |
          make test

      - name: Format code with Black
        run: |
          make format
